/**
 * Build-time writer: renders the guides (scripts/render.ts) and emits the
 * typed src/generated/content.ts the server embeds. The site is therefore
 * never a second copy of the docs — it is the docs, rendered.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, posix } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderGuides } from './render.ts';

const here = dirname(fileURLToPath(import.meta.url));
const outFile = join(here, '..', 'src', 'generated', 'content.ts');
const repoRoot = join(here, '..', '..');

const guides = await renderGuides();

const banner =
  '// GENERATED by scripts/render-content.ts — do not edit.\n// Source: docs/guides/*.md. Run `pnpm run render` to regenerate.\n';
const body = `export interface Guide {
  readonly slug: string;
  readonly title: string;
  readonly html: string;
}

export const guides: readonly Guide[] = ${JSON.stringify(guides, null, 2)};
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, `${banner}\n${body}`);
console.log(`rendered ${guides.length} guides → ${posix.relative(repoRoot, outFile)}`);
